version: "3.9" # optional since v1.27.0
services:
    tiny-house:
        build: ./server
        ports:
            - "1337:80"
        # depends_on:
        #     - swimming-pool
    swimming-pool:
        build: ./db
